/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.sql.DriverManager;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author paida
 */
public class Custom extends javax.swing.JFrame {

  Connection conn;
  int num=0;
    public Custom() {
        initComponents();
         try{
        Class.forName("com.mysql.jdbc.Driver");  
               conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/attendance","root","sai.1919");

             Statement stmt=conn.createStatement();
               ResultSet rs= stmt.executeQuery("select lecture from sec1");
               rs.last();
                jTextField1.setText(String.valueOf(rs.getInt(1)));

     

                stmt=conn.createStatement();
               rs= stmt.executeQuery("select lecture from sec2");
               rs.last();
                jTextField2.setText(String.valueOf(rs.getInt(1)));

                 stmt=conn.createStatement();
               rs= stmt.executeQuery("select lecture from sec3");
               rs.last();
                jTextField5.setText(String.valueOf(rs.getInt(1)));
                                

                 stmt=conn.createStatement();
                rs= stmt.executeQuery("select lecture from sec1");
               rs.last();
                num=num+rs.getInt(1);
                rs= stmt.executeQuery("select lecture from sec2");
               rs.last();
                num=num+rs.getInt(1);
                rs= stmt.executeQuery("select lecture from sec3");
               rs.last();
                num=num+rs.getInt(1);
                jTextField6.setText(String.valueOf(num));
     
 
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("HP Simplified", 1, 54)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CUSTOM");

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setPreferredSize(new java.awt.Dimension(500, 220));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel6.setText("Edit attendance of:");

        jComboBox5.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SEC 1", "SEC 2", "SEC 3" }));
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel7.setText("Lecture No.:");

        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel8.setText("Enrollment No:");

        jTextField4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButton4.setText("ADD");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButton6.setText("REMOVE");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 204, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jButton4)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6)))
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel2.setText("Lectures completed for:-");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setText("SEC 1   -");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel4.setText("SEC 2   -");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel5.setText("SEC 3   -");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel10.setText("TOTAL   -");

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTextField5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jTextField6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel11.setText("Total number of students:-");

        jTextField7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField7.setText("30");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel10)))
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/extra.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(158, 158, 158)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(99, 99, 99))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(576, 576, 576))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(431, 431, 431)
                        .addComponent(jButton1)
                        .addGap(67, 67, 67))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(120, 120, 120))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(136, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        User ob=new User();
        ob.setTitle("Attendance Repository");
        ob.setBounds(200,0,1500,1000);
        ob.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
             String selected=jComboBox5.getItemAt(jComboBox5.getSelectedIndex());
             String lectno=jTextField3.getText();
             String enrollno=jTextField4.getText();
                if(jTextField3.getText().length()==0)
             JOptionPane.showMessageDialog(null,"Enter Lecture number");
             try{
               PreparedStatement stmt;
             if(selected.equals("SEC 1"))
             {
                 
                 switch(enrollno){
                case "AR001":   stmt=conn.prepareStatement("update sec1 set AR001=? where lecture=?");
                                stmt.setInt(1,1);
                                stmt.setInt(2,Integer.parseInt(lectno));
                                stmt.executeUpdate();
                                 jLabel9.setText("Updated");
                                break;
                case "AR002":   stmt=conn.prepareStatement("update sec1 set AR002=? where lecture=?");
                                stmt.setInt(1,1);
                                stmt.setInt(2,Integer.parseInt(lectno));
                                stmt.executeUpdate();
                                 jLabel9.setText("Updated");
                                break;
                case "AR003":   stmt=conn.prepareStatement("update sec1 set AR003=? where lecture=?");
                                stmt.setInt(1,1);
                                stmt.setInt(2,Integer.parseInt(lectno));
                                stmt.executeUpdate();
                                 jLabel9.setText("Updated");
                                break;
                case "AR004":   stmt=conn.prepareStatement("update sec1 set AR004=? where lecture=?");
                                stmt.setInt(1,1);
                                stmt.setInt(2,Integer.parseInt(lectno));
                                stmt.executeUpdate();
                                 jLabel9.setText("Updated");
                                break;
                case "AR005":   stmt=conn.prepareStatement("update sec1 set AR005=? where lecture=?");
                                stmt.setInt(1,1);
                                stmt.setInt(2,Integer.parseInt(lectno));
                                stmt.executeUpdate();
                                 jLabel9.setText("Updated");
                                break;
                case "AR006":   stmt=conn.prepareStatement("update sec1 set AR006=? where lecture=?");
                                stmt.setInt(1,1);
                                stmt.setInt(2,Integer.parseInt(lectno));
                                stmt.executeUpdate();
                                 jLabel9.setText("Updated");
                                break;
                case "AR007":   stmt=conn.prepareStatement("update sec1 set AR007=? where lecture=?");
                                stmt.setInt(1,1);
                                stmt.setInt(2,Integer.parseInt(lectno));
                                stmt.executeUpdate();
                                 jLabel9.setText("Updated");
                                break;
                case "AR008":   stmt=conn.prepareStatement("update sec1 set AR008=? where lecture=?");
                                stmt.setInt(1,1);
                                stmt.setInt(2,Integer.parseInt(lectno));
                                stmt.executeUpdate();
                                 jLabel9.setText("Updated");
                                break;
                case "AR009":   stmt=conn.prepareStatement("update sec1 set AR009=? where lecture=?");
                                stmt.setInt(1,1);
                                stmt.setInt(2,Integer.parseInt(lectno));
                                stmt.executeUpdate();
                                 jLabel9.setText("Updated");
                                break;
                case "AR010":   stmt=conn.prepareStatement("update sec1 set AR010=? where lecture=?");
                                stmt.setInt(1,1);
                                stmt.setInt(2,Integer.parseInt(lectno));
                                stmt.executeUpdate();
                                 jLabel9.setText("Updated");
                                break;
                default: 
                                JOptionPane.showMessageDialog(null,"Enter Vaild enrollment number..");
                                break;
                 }
             }
             else if(selected.equals("SEC 2"))
             {
                   switch(enrollno){
                case "AR011":   stmt=conn.prepareStatement("update sec2 set AR011=? where lecture=?");
                                stmt.setInt(1,1);
                                stmt.setInt(2,Integer.parseInt(lectno));
                                stmt.executeUpdate();
                                 jLabel9.setText("Updated");
                                break;
                case "AR012":   stmt=conn.prepareStatement("update sec2 set AR012=? where lecture=?");
                                stmt.setInt(1,1);
                                stmt.setInt(2,Integer.parseInt(lectno));
                                stmt.executeUpdate();
                                 jLabel9.setText("Updated");
                                break;
                case "AR013":   stmt=conn.prepareStatement("update sec2 set AR013=? where lecture=?");
                                stmt.setInt(1,1);
                                stmt.setInt(2,Integer.parseInt(lectno));
                                stmt.executeUpdate();
                                 jLabel9.setText("Updated");
                                break;
                case "AR014":   stmt=conn.prepareStatement("update sec2 set AR014=? where lecture=?");
                                stmt.setInt(1,1);
                                stmt.setInt(2,Integer.parseInt(lectno));
                                stmt.executeUpdate();
                                 jLabel9.setText("Updated");
                                break;
                case "AR015":   stmt=conn.prepareStatement("update sec2 set AR015=? where lecture=?");
                                stmt.setInt(1,1);
                                stmt.setInt(2,Integer.parseInt(lectno));
                                stmt.executeUpdate();
                                 jLabel9.setText("Updated");
                                break;
                case "AR016":   stmt=conn.prepareStatement("update sec2 set AR016=? where lecture=?");
                                stmt.setInt(1,1);
                                stmt.setInt(2,Integer.parseInt(lectno));
                                stmt.executeUpdate();
                                 jLabel9.setText("Updated");
                                break;
                case "AR017":   stmt=conn.prepareStatement("update sec2 set AR017=? where lecture=?");
                                stmt.setInt(1,1);
                                stmt.setInt(2,Integer.parseInt(lectno));
                                stmt.executeUpdate();
                                 jLabel9.setText("Updated");
                                break;
                case "AR018":   stmt=conn.prepareStatement("update sec2 set AR018=? where lecture=?");
                                stmt.setInt(1,1);
                                stmt.setInt(2,Integer.parseInt(lectno));
                                stmt.executeUpdate();
                                 jLabel9.setText("Updated");
                                break;
                case "AR019":   stmt=conn.prepareStatement("update sec2 set AR019=? where lecture=?");
                                stmt.setInt(1,1);
                                stmt.setInt(2,Integer.parseInt(lectno));
                                stmt.executeUpdate();
                                 jLabel9.setText("Updated");
                                break;
                case "AR020":   stmt=conn.prepareStatement("update sec2 set AR020=? where lecture=?");
                                stmt.setInt(1,1);
                                stmt.setInt(2,Integer.parseInt(lectno));
                                stmt.executeUpdate();
                                 jLabel9.setText("Updated");
                                break;
                default: 
                                JOptionPane.showMessageDialog(null,"Enter Vaild enrollment number..");
                                break;
                 }
             }
             else
             {
                switch(enrollno){
                case "AR021":   stmt=conn.prepareStatement("update sec3 set AR021=? where lecture=?");
                                stmt.setInt(1,1);
                                stmt.setInt(2,Integer.parseInt(lectno));
                                stmt.executeUpdate();
                                 jLabel9.setText("Updated");
                                break;
                case "AR022":   stmt=conn.prepareStatement("update sec3 set AR022=? where lecture=?");
                                stmt.setInt(1,1);
                                stmt.setInt(2,Integer.parseInt(lectno));
                                stmt.executeUpdate();
                                 jLabel9.setText("Updated");
                                break;
                case "AR023":   stmt=conn.prepareStatement("update sec3 set AR023=? where lecture=?");
                                stmt.setInt(1,1);
                                stmt.setInt(2,Integer.parseInt(lectno));
                                stmt.executeUpdate();
                                 jLabel9.setText("Updated");
                                break;
                case "AR024":   stmt=conn.prepareStatement("update sec3 set AR024=? where lecture=?");
                                stmt.setInt(1,1);
                                stmt.setInt(2,Integer.parseInt(lectno));
                                stmt.executeUpdate();
                                 jLabel9.setText("Updated");
                                break;
                case "AR025":   stmt=conn.prepareStatement("update sec3 set AR025=? where lecture=?");
                                stmt.setInt(1,1);
                                stmt.setInt(2,Integer.parseInt(lectno));
                                stmt.executeUpdate();
                                 jLabel9.setText("Updated");
                                break;
                case "AR026":   stmt=conn.prepareStatement("update sec3 set AR026=? where lecture=?");
                                stmt.setInt(1,1);
                                stmt.setInt(2,Integer.parseInt(lectno));
                                stmt.executeUpdate();
                                 jLabel9.setText("Updated");
                                break;
                case "AR027":   stmt=conn.prepareStatement("update sec3 set AR027=? where lecture=?");
                                stmt.setInt(1,1);
                                stmt.setInt(2,Integer.parseInt(lectno));
                                stmt.executeUpdate();
                                 jLabel9.setText("Updated");
                                break;
                case "AR028":   stmt=conn.prepareStatement("update sec3 set AR028=? where lecture=?");
                                stmt.setInt(1,1);
                                stmt.setInt(2,Integer.parseInt(lectno));
                                stmt.executeUpdate();
                                 jLabel9.setText("Updated");
                                break;
                case "AR029":   stmt=conn.prepareStatement("update sec3 set AR029=? where lecture=?");
                                stmt.setInt(1,1);
                                stmt.setInt(2,Integer.parseInt(lectno));
                                stmt.executeUpdate();
                                 jLabel9.setText("Updated");
                                break;
                case "AR030":   stmt=conn.prepareStatement("update sec3 set AR030=? where lecture=?");
                                stmt.setInt(1,1);
                                stmt.setInt(2,Integer.parseInt(lectno));
                                stmt.executeUpdate();
                                 jLabel9.setText("Updated");
                                break;
                default: 
                             JOptionPane.showMessageDialog(null,"Enter Vaild enrollment number..");
                             break;
                 }
               
             }

             conn.close();
             }
    
    catch(SQLException e){
    System.out.println(e);
    }
    
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
           String selected=jComboBox5.getItemAt(jComboBox5.getSelectedIndex());
             String lectno=jTextField3.getText();
             String enrollno=jTextField4.getText();
                if(jTextField3.getText().length()==0)
             JOptionPane.showMessageDialog(null,"Enter Lecture number");
             try{
               PreparedStatement stmt;
             if(selected.equals("SEC 1"))
             {
                 
                 switch(enrollno){
                case "AR001":   stmt=conn.prepareStatement("update sec1 set AR001=? where lecture=?");
                                stmt.setInt(1,0);
                                stmt.setInt(2,Integer.parseInt(lectno));
                                stmt.executeUpdate();
                                 jLabel9.setText("Updated");
                                break;
                case "AR002":   stmt=conn.prepareStatement("update sec1 set AR002=? where lecture=?");
                                stmt.setInt(1,0);
                                stmt.setInt(2,Integer.parseInt(lectno));
                                stmt.executeUpdate();
                                 jLabel9.setText("Updated");
                                break;
                case "AR003":   stmt=conn.prepareStatement("update sec1 set AR003=? where lecture=?");
                                stmt.setInt(1,0);
                                stmt.setInt(2,Integer.parseInt(lectno));
                                stmt.executeUpdate();
                                 jLabel9.setText("Updated");
                                break;
                case "AR004":   stmt=conn.prepareStatement("update sec1 set AR004=? where lecture=?");
                                stmt.setInt(1,0);
                                stmt.setInt(2,Integer.parseInt(lectno));
                                stmt.executeUpdate();
                                 jLabel9.setText("Updated");
                                break;
                case "AR005":   stmt=conn.prepareStatement("update sec1 set AR005=? where lecture=?");
                                stmt.setInt(1,0);
                                stmt.setInt(2,Integer.parseInt(lectno));
                                stmt.executeUpdate();
                                 jLabel9.setText("Updated");
                                break;
                case "AR006":   stmt=conn.prepareStatement("update sec1 set AR006=? where lecture=?");
                                stmt.setInt(1,0);
                                stmt.setInt(2,Integer.parseInt(lectno));
                                stmt.executeUpdate();
                                 jLabel9.setText("Updated");
                                break;
                case "AR007":   stmt=conn.prepareStatement("update sec1 set AR007=? where lecture=?");
                                stmt.setInt(1,0);
                                stmt.setInt(2,Integer.parseInt(lectno));
                                stmt.executeUpdate();
                                 jLabel9.setText("Updated");
                                break;
                case "AR008":   stmt=conn.prepareStatement("update sec1 set AR008=? where lecture=?");
                                stmt.setInt(1,0);
                                stmt.setInt(2,Integer.parseInt(lectno));
                                stmt.executeUpdate();
                                 jLabel9.setText("Updated");
                                break;
                case "AR009":   stmt=conn.prepareStatement("update sec1 set AR009=? where lecture=?");
                                stmt.setInt(1,0);
                                stmt.setInt(2,Integer.parseInt(lectno));
                                stmt.executeUpdate();
                                 jLabel9.setText("Updated");
                                break;
                case "AR010":   stmt=conn.prepareStatement("update sec1 set AR010=? where lecture=?");
                                stmt.setInt(1,0);
                                stmt.setInt(2,Integer.parseInt(lectno));
                                stmt.executeUpdate();
                                 jLabel9.setText("Updated");
                                break;
                default: 
                                JOptionPane.showMessageDialog(null,"Enter Vaild enrollment number..");
                                break;
                 }
             }
             else if(selected.equals("SEC 2"))
             {
                   switch(enrollno){
                case "AR011":   stmt=conn.prepareStatement("update sec2 set AR011=? where lecture=?");
                                stmt.setInt(1,0);
                                stmt.setInt(2,Integer.parseInt(lectno));
                                stmt.executeUpdate();
                                 jLabel9.setText("Updated");
                                break;
                case "AR012":   stmt=conn.prepareStatement("update sec2 set AR012=? where lecture=?");
                                stmt.setInt(1,0);
                                stmt.setInt(2,Integer.parseInt(lectno));
                                stmt.executeUpdate();
                                 jLabel9.setText("Updated");
                                break;
                case "AR013":   stmt=conn.prepareStatement("update sec2 set AR013=? where lecture=?");
                                stmt.setInt(1,0);
                                stmt.setInt(2,Integer.parseInt(lectno));
                                stmt.executeUpdate();
                                 jLabel9.setText("Updated");
                                break;
                case "AR014":   stmt=conn.prepareStatement("update sec2 set AR014=? where lecture=?");
                                stmt.setInt(1,0);
                                stmt.setInt(2,Integer.parseInt(lectno));
                                stmt.executeUpdate();
                                 jLabel9.setText("Updated");
                                break;
                case "AR015":   stmt=conn.prepareStatement("update sec2 set AR015=? where lecture=?");
                                stmt.setInt(1,0);
                                stmt.setInt(2,Integer.parseInt(lectno));
                                stmt.executeUpdate();
                                 jLabel9.setText("Updated");
                                break;
                case "AR016":   stmt=conn.prepareStatement("update sec2 set AR016=? where lecture=?");
                                stmt.setInt(1,0);
                                stmt.setInt(2,Integer.parseInt(lectno));
                                stmt.executeUpdate();
                                 jLabel9.setText("Updated");
                                break;
                case "AR017":   stmt=conn.prepareStatement("update sec2 set AR017=? where lecture=?");
                                stmt.setInt(1,0);
                                stmt.setInt(2,Integer.parseInt(lectno));
                                stmt.executeUpdate();
                                 jLabel9.setText("Updated");
                                break;
                case "AR018":   stmt=conn.prepareStatement("update sec2 set AR018=? where lecture=?");
                                stmt.setInt(1,0);
                                stmt.setInt(2,Integer.parseInt(lectno));
                                stmt.executeUpdate();
                                 jLabel9.setText("Updated");
                                break;
                case "AR019":   stmt=conn.prepareStatement("update sec2 set AR019=? where lecture=?");
                                stmt.setInt(1,0);
                                stmt.setInt(2,Integer.parseInt(lectno));
                                stmt.executeUpdate();
                                 jLabel9.setText("Updated");
                                break;
                case "AR020":   stmt=conn.prepareStatement("update sec2 set AR020=? where lecture=?");
                                stmt.setInt(1,0);
                                stmt.setInt(2,Integer.parseInt(lectno));
                                stmt.executeUpdate();
                                 jLabel9.setText("Updated");
                                break;
                default: 
                                JOptionPane.showMessageDialog(null,"Enter Vaild enrollment number..");
                                break;
                 }
             }
             else
             {
                switch(enrollno){
                case "AR021":   stmt=conn.prepareStatement("update sec3 set AR021=? where lecture=?");
                                stmt.setInt(1,0);
                                stmt.setInt(2,Integer.parseInt(lectno));
                                stmt.executeUpdate();
                                 jLabel9.setText("Updated");
                                break;
                case "AR022":   stmt=conn.prepareStatement("update sec3 set AR022=? where lecture=?");
                                stmt.setInt(1,0);
                                stmt.setInt(2,Integer.parseInt(lectno));
                                stmt.executeUpdate();
                                 jLabel9.setText("Updated");
                                break;
                case "AR023":   stmt=conn.prepareStatement("update sec3 set AR023=? where lecture=?");
                                stmt.setInt(1,0);
                                stmt.setInt(2,Integer.parseInt(lectno));
                                stmt.executeUpdate();
                                 jLabel9.setText("Updated");
                                break;
                case "AR024":   stmt=conn.prepareStatement("update sec3 set AR024=? where lecture=?");
                                stmt.setInt(1,0);
                                stmt.setInt(2,Integer.parseInt(lectno));
                                stmt.executeUpdate();
                                 jLabel9.setText("Updated");
                                break;
                case "AR025":   stmt=conn.prepareStatement("update sec3 set AR025=? where lecture=?");
                                stmt.setInt(1,0);
                                stmt.setInt(2,Integer.parseInt(lectno));
                                stmt.executeUpdate();
                                 jLabel9.setText("Updated");
                                break;
                case "AR026":   stmt=conn.prepareStatement("update sec3 set AR026=? where lecture=?");
                                stmt.setInt(1,0);
                                stmt.setInt(2,Integer.parseInt(lectno));
                                stmt.executeUpdate();
                                 jLabel9.setText("Updated");
                                break;
                case "AR027":   stmt=conn.prepareStatement("update sec3 set AR027=? where lecture=?");
                                stmt.setInt(1,0);
                                stmt.setInt(2,Integer.parseInt(lectno));
                                stmt.executeUpdate();
                                 jLabel9.setText("Updated");
                                break;
                case "AR028":   stmt=conn.prepareStatement("update sec3 set AR028=? where lecture=?");
                                stmt.setInt(1,0);
                                stmt.setInt(2,Integer.parseInt(lectno));
                                stmt.executeUpdate();
                                 jLabel9.setText("Updated");
                                break;
                case "AR029":   stmt=conn.prepareStatement("update sec3 set AR029=? where lecture=?");
                                stmt.setInt(1,0);
                                stmt.setInt(2,Integer.parseInt(lectno));
                                stmt.executeUpdate();
                                 jLabel9.setText("Updated");
                                break;
                case "AR030":   stmt=conn.prepareStatement("update sec3 set AR030=? where lecture=?");
                                stmt.setInt(1,0);
                                stmt.setInt(2,Integer.parseInt(lectno));
                                stmt.executeUpdate();
                                 jLabel9.setText("Updated");
                                break;
                default: 
                             JOptionPane.showMessageDialog(null,"Enter Vaild enrollment number..");
                             break;
                 }
               
             }

             conn.close();
             }
    
    catch(SQLException e){
    System.out.println(e);
    }
                      
             
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
          try{
         Statement stmt=conn.createStatement();
               ResultSet rs= stmt.executeQuery("select lecture from sec1");
               rs.last();
                jTextField1.setText(String.valueOf(rs.getInt(1)));
     }
      catch(Exception e)
        {
            System.out.println(e);
        }
     
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
          try{
         Statement stmt=conn.createStatement();
               ResultSet rs= stmt.executeQuery("select lecture from sec2");
               rs.last();
                jTextField2.setText(String.valueOf(rs.getInt(1)));
     }
      catch(Exception e)
        {
            System.out.println(e);
        }
     
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
          try{
         Statement stmt=conn.createStatement();
               ResultSet rs= stmt.executeQuery("select lecture from sec3");
               rs.last();
                jTextField5.setText(String.valueOf(rs.getInt(1)));
     }
      catch(Exception e)
        {
            System.out.println(e);
        }
     
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
        int num=0;
          try{
         Statement stmt=conn.createStatement();
               ResultSet rs= stmt.executeQuery("select lecture from sec1");
               rs.last();
                num=num+rs.getInt(1);
                rs= stmt.executeQuery("select lecture from sec2");
               rs.last();
                num=num+rs.getInt(1);
                rs= stmt.executeQuery("select lecture from sec3");
               rs.last();
                num=num+rs.getInt(1);
                jTextField6.setText(String.valueOf(rs.getInt(1)));
     }
      catch(Exception e)
        {
            System.out.println(e);
        }
     
    }//GEN-LAST:event_jTextField6ActionPerformed


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Custom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Custom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Custom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Custom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Custom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
